Repository DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY, pull requests merged in 2022-12, with the labels that each got.

#127 [Fix] 리뷰 등록 이미지 처리 및 맛집리스트 새로고침 버그 수정
  Projects/App/Sources/Domain/Place/PlaceList/PlaceUseCase.swift
  Projects/App/Sources/Domain/Review/ReviewRegisterUseCase.swift
  Projects/App/Sources/UI/Place/PlaceList/ViewModel/PlaceListViewModel.swift
  Projects/App/Sources/UI/Review/View/ReviewRegisterViewController.swift
  Projects/App/Sources/UI/Review/View/Views/ReviewCardView.swift
  Projects/App/Sources/UI/Review/ViewModel/ReviewRegisterViewModel.swift
Labels: bug, Fix

#126 [Fix] 앱 로그인 인증대학 없음 버그 수정
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Sources/Domain/User/UserInfoManager.swift
  Projects/App/Sources/Domain/User/UserInfoManagerUseCase.swift
  Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
  Projects/App/Sources/UI/User/Login/ViewModel/ThirdPartyLoginViewModel.swift
Labels: Fix

#129 [Setting] 빌드버전 1.2로 설정
  Projects/App/Sources/Application/Info.plist
Labels: setting
