Repository DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY, pull requests merged in 2022-10, with the labels that each got.

#14 [Setting] 프로젝트 Tuist 초기 셋팅 및 PR 템플릿과 auto_assign 적용
  .github/.auto_assign.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .package.resolved
  .tuist-version
  Projects/App/.package.resolved
  Projects/App/.swiftlint.yml
  Projects/App/Project.swift
  Projects/App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/App/Resources/Assets.xcassets/Contents.json
  Projects/App/Resources/LaunchScreen.storyboard
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/App/Sources/Application/Info.plist
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Sources/Application/ViewController.swift
  Projects/App/Sources/Domain/Organization/DomainOrganizationPlaceHolder.swift
  Projects/App/Sources/Domain/Place/DomainPlacePlaceHolder.swift
  Projects/App/Sources/Domain/Review/DomainReviewPlaceHolder.swift
  Projects/App/Sources/Domain/User/DomainUserPlaceHolder.swift
  Projects/App/Sources/Global/Extension/ExtensionPlaceHolder.swift
  Projects/App/Sources/Global/Utility/UtilityPlaceHolder.swift
  Projects/App/Sources/UI/Organization/UIOrganizationPlaceHolder.swift
  Projects/App/Sources/UI/Place/UIPlacePlaceHolder.swift
  Projects/App/Sources/UI/Review/UIReviewPlaceHolder.swift
  Projects/App/Sources/UI/User/UIUserPlaceHolder.swift
  Projects/App/Tests/.gitkeep
  Projects/DesignSystem/Project.swift
  Projects/DesignSystem/Resources/Assets.xcassets/Contents.json
  Projects/DesignSystem/Sources/Asset/SourcesAssetHolder.swift
  Projects/DesignSystem/Sources/Color/SourcesColorHolder.swift
  Projects/DesignSystem/Sources/Font/SourcesFontHolder.swift
  Projects/DesignSystem/Tests/.gitkeep
  Projects/Network/Project.swift
  Projects/Network/Sources/API/APIPlaceHolder.swift
  Projects/Network/Sources/DTO/DTOPlaceHolder.swift
  Projects/Network/Sources/EndPoint/EndPointPlaceHolder.swift
  Projects/Network/Sources/Manager/ManagerPlaceHolder.swift
  Projects/Network/Tests/NetworkTests.swift
  Tuist/Config.swift
  Tuist/ProjectDescriptionHelpers/Dependency+Project.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/ProjectDescriptionHelpers/Scripts.swift
  Workspace.swift
Labels: 🌊 Goban, tuist, setting

#21 [Setting] 디자인 시스템 Asset 및 Color Extension 추가
  Projects/DesignSystem/Resources/Colors.xcassets/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/grayC5.colorset/Contents.json
  Projects/DesignSystem/Sources/Asset/Asset.swift
  Projects/DesignSystem/Sources/Asset/SourcesAssetHolder.swift
  Projects/DesignSystem/Sources/Asset/UIImage+.swift
  Projects/DesignSystem/Sources/Color/Color.swift
  Projects/DesignSystem/Sources/Color/SourcesColorHolder.swift
  Projects/DesignSystem/Sources/Color/UIColor+.swift
Labels: 🎄 Avery, setting

#24 [Feat] 도메인 레이어 모델 및 Mock Data 추가
  Projects/App/Sources/Domain/Category/Category.swift
  Projects/App/Sources/Domain/MockData/MockData.swift
  Projects/App/Sources/Domain/Organization/DomainOrganizationPlaceHolder.swift
  Projects/App/Sources/Domain/Organization/Organization.swift
  Projects/App/Sources/Domain/Place/DomainPlacePlaceHolder.swift
  Projects/App/Sources/Domain/Place/Place.swift
  Projects/App/Sources/Domain/Review/DomainReviewPlaceHolder.swift
  Projects/App/Sources/Domain/Review/Review.swift
  Projects/App/Sources/Domain/User/DomainUserPlaceHolder.swift
  Projects/App/Sources/Domain/User/User.swift
Labels: 🎄 Avery, setting

#26 [Setting] SwiftUI Preview utility 추가
  Projects/App/Sources/Application/ViewController.swift
  Projects/App/Sources/Application/ViewControllerTemplate.swift
  Projects/DesignSystem/Sources/Utility/+Preview.swift
Labels: setting, UI

#27 [Fix] Mock Data 오류 수정
  Projects/App/Sources/Domain/MockData/MockData.swift
Labels: bug, 🎄 Avery

#25 [Feat] multipart/form-data 통신
  Projects/Network/Sources/EndPoint/Endpoint.swift
  Projects/Network/Sources/EndPoint/Requestable.swift
Labels: 네트워킹

#28 [Feat] ViewController 템플릿추가
  Scripts/ZESTY_VC.xctemplate/TemplateIcon-1016.png
  Scripts/ZESTY_VC.xctemplate/TemplateIcon-1016@2x.png
  Scripts/ZESTY_VC.xctemplate/TemplateInfo.plist
  Scripts/ZESTY_VC.xctemplate/___FILEBASENAME___ViewController.swift
  Scripts/set_template.sh
Labels: 🎄 Avery, setting

#35 [Setting] Alamofire 와 KakaoSDK dependency 수정
  .package.resolved
  Projects/App/Project.swift
Labels: setting

#30 [Feat] 닉네임 검증 activityIndicator UI 구현
  Projects/App/Sources/UI/User/Signup/View/NickNameInputViewController.swift
  Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
  Projects/DesignSystem/Sources/Component/ShadowButtonView.swift
Labels: 🌊 Goban, UI

#31 [FEAT] 대학교 리스트 화면 UI
  Projects/App/Sources/UI/Organization/OrganizationList/View/Cell/OrganizationListCell.swift
  Projects/App/Sources/UI/Organization/OrganizationList/View/OrganizationListViewController.swift
  Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
  Projects/App/Sources/UI/Organization/UIOrganizationPlaceHolder.swift
  Projects/App/Sources/UI/User/Login/View/ThirdPartyLoginViewController.swift
  Projects/DesignSystem/Resources/Assets.xcassets/magnifyingglass.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/magnifyingglass.imageset/magnifyingglass@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/magnifyingglass.imageset/magnifyingglass@3x.png
  Projects/DesignSystem/Sources/Asset/Asset.swift
  Projects/DesignSystem/Sources/Component/ShadowTextFieldView.swift
Labels: 🦊 Nick, UI

#36 [Chore] : ShadowTextFieldView leftImage 변경
  Projects/DesignSystem/Resources/Assets.xcassets/magnifyingglass.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/magnifyingglass.imageset/magnifyingglass@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/magnifyingglass.imageset/magnifyingglass@3x.png
  Projects/DesignSystem/Sources/Asset/Asset.swift
  Projects/DesignSystem/Sources/Component/ShadowTextFieldView.swift
Labels: 🦊 Nick, UI

#33 [Feat] 맛집리스트 레이아웃
  Projects/App/Sources/UI/Place/PlaceList/View/Cell/PickedPlaceCell.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Cell/WholePlaceCell.swift
  Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Views/BannerView.swift
  Projects/App/Sources/UI/Place/UIPlacePlaceHolder.swift
Labels: UI

#39 [Feat] 맛집리스트 UI (구버전)
  Projects/App/Sources/UI/Place/PlaceList/View/Cell/PickedPlaceCell.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Cell/WholePlaceCell.swift
  Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Views/BannerSubview.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Views/BannerView.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Views/PlaceListHeaderView.swift
Labels: UI

#41 [Setting] MainTitleView 컴포넌트 추가
  Projects/DesignSystem/Sources/Color/Color.swift
  Projects/DesignSystem/Sources/Component/MainTitleView.swift
Labels: 디자인패턴, 🦊 Nick, setting

#38 [Feat] API 작성 및 에러 핸들링
  .gitignore
  Projects/App/Sources/Domain/Organization/Organization.swift
  Projects/App/Sources/Domain/Organization/OrganizationUseCase.swift
  Projects/App/Sources/Domain/Place/Place.swift
  Projects/App/Sources/Domain/Place/PlaceUseCase.swift
  Projects/App/Sources/Domain/Review/Review.swift
  Projects/App/Sources/Domain/User/UserUseCase.swift
  Projects/Network/.swiftlint.yml
  Projects/Network/Sources/API/APIPlaceHolder.swift
  Projects/Network/Sources/API/CategoryAPI.swift
  Projects/Network/Sources/API/OrganizationAPI.swift
  Projects/Network/Sources/API/PlaceAPI.swift
  Projects/Network/Sources/API/ReviewAPI.swift
  Projects/Network/Sources/API/UserAPI.swift
  Projects/Network/Sources/DTO/DTOPlaceHolder.swift
  Projects/Network/Sources/DTO/RequestDTO/OrganizationListDTO.swift
  Projects/Network/Sources/DTO/RequestDTO/PlaceListDTO.swift
  Projects/Network/Sources/DTO/RequestDTO/SignUpUserDTO.swift
  Projects/Network/Sources/DTO/ResponseDTO/DTOPlaceHolder.swift
  Projects/Network/Sources/EndPoint/Endpoint.swift
  Projects/Network/Sources/EndPoint/Requestable.swift
  Projects/Network/Sources/Service/NetworkError.swift
  Projects/Network/Sources/Service/NetworkService.swift
Labels: 네트워킹, Combine

#43 [Design] 로그인 / 회원가입 UI
  Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
  Projects/App/Sources/UI/User/Login/View/ThirdPartyLoginViewController.swift
  Projects/App/Sources/UI/User/Signup/View/NickNameInputViewController.swift
  Projects/App/Sources/UI/User/Signup/View/SignupCompleteViewController.swift
  Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
  Projects/DesignSystem/Resources/Assets.xcassets/btn_applelogin.imageset/btn_applelogin.png
  Projects/DesignSystem/Resources/Assets.xcassets/btn_kakaologin.imageset/btn_kakaologin.png
  Projects/DesignSystem/Resources/Assets.xcassets/img_login.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_login.imageset/img_login.png
  Projects/DesignSystem/Resources/Assets.xcassets/img_signup.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_signup.imageset/img_signup.png
  Projects/DesignSystem/Resources/Assets.xcassets/img_zesterone.imageset/img_zesterone.png
  Projects/DesignSystem/Resources/Assets.xcassets/img_zesterthree.imageset/img_zesterthree.png
  Projects/DesignSystem/Resources/Colors.xcassets/gray3C3C43.colorset/Contents.json
  Projects/DesignSystem/Sources/Asset/Asset.swift
  Projects/DesignSystem/Sources/Component/ArrowButton.swift
  Projects/DesignSystem/Sources/Component/FullWidthBlackButton.swift
  Projects/DesignSystem/Sources/Component/ShadowButtonView.swift
Labels: UI

#44 [Feat] 맛집상세페이지 UI
  Projects/App/Sources/Domain/MockData/MockData.swift
  Projects/App/Sources/Global/Extension/UIScreen+.swift
  Projects/App/Sources/Global/Utility/UrlUtils.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/CategoryCell.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/EmptyReviewCell.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/ReviewCell.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/PlaceDetailViewController.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/Views/CategoryCollectionView.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/Views/EvaluationItemView.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/Views/PlaceDetailHeaderView.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/Views/PlaceInfoHeaderView.swift
  Projects/DesignSystem/Resources/Assets.xcassets/btn_basic/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/btn_basic/btn_applelogin.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/btn_basic/btn_applelogin.imageset/btn_applelogin.png
  Projects/DesignSystem/Resources/Assets.xcassets/btn_basic/btn_kakaologin.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/btn_basic/btn_kakaologin.imageset/btn_kakaologin.png
  Projects/DesignSystem/Resources/Assets.xcassets/btn_basic/btn_kakaomap.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/btn_basic/btn_kakaomap.imageset/btn_kakaomap.svg
  Projects/DesignSystem/Resources/Assets.xcassets/btn_basic/btn_navermap.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/btn_basic/btn_navermap.imageset/btn_navermap.svg
  Projects/DesignSystem/Resources/Assets.xcassets/btn_basic/btn_side_plus.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/btn_basic/btn_side_plus.imageset/btn_side_plus.svg
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_bad_25.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_bad_25.imageset/img_reviewfriends_bad_25.svg
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_bad_30.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_bad_30.imageset/img_reviewfriends_bad_30.svg
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_bad_45.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_bad_45.imageset/img_reviewfriends_bad_45.svg
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_bad_60.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_bad_60.imageset/img_reviewfriends_bad_60.svg
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_good_25.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_good_25.imageset/img_reviewfriends_good_25.svg
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_good_30.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_good_30.imageset/img_reviewfriends_good_30.svg
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_good_45.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_good_45.imageset/img_reviewfriends_good_45.svg
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_good_60.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_good_60.imageset/img_reviewfriends_good_60.svg
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_soso_25.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_soso_25.imageset/img_reviewfriends_soso_25.svg
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_soso_30.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_soso_30.imageset/img_reviewfriends_soso_30.svg
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_soso_45.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_soso_45.imageset/img_reviewfriends_sos_45.svg
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_soso_60.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_soso_60.imageset/img_reviewfriends_soso_60.svg
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_together.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_together.imageset/img_reviewfriends_together.svg
  Projects/DesignSystem/Resources/Colors.xcassets/background.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/dim.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/disabled.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/grayF6.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/whiteEBEBF5.colorset/Contents.json
  Projects/DesignSystem/Sources/Asset/Asset.swift
  Projects/DesignSystem/Sources/Color/Color.swift
  Projects/DesignSystem/Sources/Label/BasePaddingLabel.swift
  Projects/DesignSystem/Sources/View/UIVIew+.swift
Labels: 🎄 Avery, UI

#49 [Design] review card UI
  Projects/App/Sources/UI/Review/EvaluationViewController.swift
  Projects/App/Sources/UI/Review/ReviewCardViewController.swift
  Projects/App/Sources/UI/Review/ReviewRegisterViewController.swift
  Projects/App/Sources/UI/Review/Views/EvaluationButton.swift
  Projects/App/Sources/UI/Review/Views/ReviewCardView.swift
  Projects/DesignSystem/Resources/Assets.xcassets/img_mockmenu.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_mockmenu.imageset/victoria-shes-UC0HZdUitWY-unsplash.jpg
  Projects/DesignSystem/Sources/Asset/Asset.swift
  Projects/DesignSystem/Sources/Component/PaddingLabel.swift
  Projects/DesignSystem/Sources/Extension/UIFont+.swift
  Projects/DesignSystem/Sources/Extension/UIView+.swift
Labels: UI

#45 [Design] 리뷰 등록 UI
  Projects/App/Sources/UI/Review/EvaluationViewController.swift
  Projects/App/Sources/UI/Review/ReviewCardViewController.swift
  Projects/App/Sources/UI/Review/ReviewRegisterViewController.swift
  Projects/App/Sources/UI/Review/UIReviewPlaceHolder.swift
  Projects/App/Sources/UI/Review/Views/EvaluationButton.swift
  Projects/App/Sources/UI/Review/Views/ReviewCardView.swift
  Projects/DesignSystem/Resources/Assets.xcassets/img_mockmenu.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_mockmenu.imageset/victoria-shes-UC0HZdUitWY-unsplash.jpg
  Projects/DesignSystem/Resources/Assets.xcassets/willbeDeleted/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/willbeDeleted/img_reviewfriends_bad.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/willbeDeleted/img_reviewfriends_bad.imageset/img_reviewfriends_bad.svg
  Projects/DesignSystem/Resources/Assets.xcassets/willbeDeleted/img_reviewfriends_good.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/willbeDeleted/img_reviewfriends_good.imageset/img_reviewfriends_good.svg
  Projects/DesignSystem/Resources/Assets.xcassets/willbeDeleted/img_reviewfriends_soso.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/willbeDeleted/img_reviewfriends_soso.imageset/img_reviewfriends_soso.svg
  Projects/DesignSystem/Sources/Asset/Asset.swift
  Projects/DesignSystem/Sources/Component/PaddingLabel.swift
  Projects/DesignSystem/Sources/Extension/UIFont+.swift
  Projects/DesignSystem/Sources/Extension/UIView+.swift
Labels: UI

#48 [Feat] OAuth kakao 로그인 구현
  .gitignore
  Projects/App/Project.swift
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/App/Sources/Application/Info.plist
  Projects/App/Sources/Domain/User/UserLoginUseCase.swift
  Projects/App/Sources/Domain/User/UserSignupUseCase.swift
  Projects/App/Sources/Domain/User/UserUseCase.swift
  Projects/App/Sources/Global/Extension/UserDefaults+.swift
  Projects/App/Sources/UI/User/Login/View/ThirdPartyLoginViewController.swift
  Projects/App/Sources/UI/User/Login/ViewModel/ThirdPartyLoginViewModel.swift
  Projects/App/Sources/UI/User/Signup/View/NickNameInputViewController.swift
  Projects/App/Sources/UI/User/Signup/View/SignupCompleteViewController.swift
  Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
  Projects/App/Sources/UI/User/Signup/ViewModel/SignupCompleteViewModel.swift
  Projects/Network/Sources/API/UserAPI.swift
  Projects/Network/Sources/DTO/ResponseDTO/DTOPlaceHolder.swift
  Projects/Network/Sources/DTO/ResponseDTO/OrganizationListDTO.swift
  Projects/Network/Sources/DTO/ResponseDTO/PlaceListDTO.swift
  Projects/Network/Sources/DTO/ResponseDTO/UserOauthDTO.swift
  Projects/Network/Sources/Service/NetworkService.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: 네트워킹

#51 [Design] 장소추가 UI (카테고리, 완료)
  Projects/App/Sources/Domain/Category/Category.swift
  Projects/App/Sources/Domain/MockData/MockData.swift
  Projects/App/Sources/Global/Extension/CALayer+.swift
  Projects/App/Sources/Global/Extension/UIDevice+.swift
  Projects/App/Sources/Global/Extension/UIScreen+.swift
  Projects/App/Sources/UI/Place/AddPlace/AddCategoryViewController.swift
  Projects/App/Sources/UI/Place/AddPlace/AddPlaceResultViewController.swift
  Projects/App/Sources/UI/Place/AddPlace/View/Cell/CategoryIconCell.swift
  Projects/App/Sources/UI/Place/AddPlace/ViewModel/AddPlaceViewModel.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/PlaceDetailViewController.swift
  Projects/DesignSystem/Resources/Assets.xcassets/img_ticket_bg.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_ticket_bg.imageset/img_ticket_bg.svg
  Projects/DesignSystem/Resources/Assets.xcassets/img_ticket_bottom.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_ticket_bottom.imageset/img_ticket_bottom.svg
  Projects/DesignSystem/Resources/Assets.xcassets/img_ticket_top.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_ticket_top.imageset/img_ticket_top.svg
  Projects/DesignSystem/Resources/Colors.xcassets/gray3C.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/point.colorset/Contents.json
  Projects/DesignSystem/Sources/Asset/Asset.swift
  Projects/DesignSystem/Sources/Color/Color.swift
Labels: UI

#52 [Design] 장소등록검색 UI
  Projects/App/Sources/Global/Extension/UITableView+.swift
  Projects/App/Sources/Global/Extension/UIView+.swift
  Projects/App/Sources/UI/Place/AddPlace/AddPlaceSearchViewController.swift
  Projects/App/Sources/UI/Place/AddPlace/View/Cell/SearchResultCell.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/PlaceDetailViewController.swift
  Projects/DesignSystem/Resources/Assets.xcassets/img_emptyfriends/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_emptyfriends/img_emptyfriends_noresult.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_emptyfriends/img_emptyfriends_noresult.imageset/img_emptyfriends_noresult.svg
  Projects/DesignSystem/Resources/Assets.xcassets/img_emptyfriends/img_emptyfriends_search.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_emptyfriends/img_emptyfriends_search.imageset/img_emptyfriends_search.svg
  Projects/DesignSystem/Sources/Asset/Asset.swift
  Projects/DesignSystem/Sources/TextField/SearchTextField.swift
Labels: UI

#53 [Setting] Firebase Analytics 사용을 위한 세팅
  .package.resolved
  Projects/App/Project.swift
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/App/Sources/Application/GoogleService-Info.plist
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: 🥒 Min, setting

#60 [Setting] AWSS3 package 추가
  .package.resolved
  Projects/App/Project.swift
  Projects/Network/Project.swift
Labels: tuist, dependency

#50 [Feat] PlaceDetail - 장소정보 데이터작업
  Projects/App/Sources/Domain/MockData/MockData.swift
  Projects/App/Sources/Domain/Place/Place.swift
  Projects/App/Sources/Domain/Place/PlaceDetail/PlaceDetailUseCase.swift
  Projects/App/Sources/Global/Extension/CALayer+.swift
  Projects/App/Sources/Global/Extension/UINavigationController+.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/ReviewCell.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/PlaceDetailViewController.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/Views/PlaceInfoHeaderView.swift
  Projects/App/Sources/UI/Place/PlaceDetail/ViewModel/PlaceDetailViewModel.swift
  Projects/Network/Sources/API/PlaceAPI.swift
  Projects/Network/Sources/DTO/RequestDTO/Place/PlaceDetailDTO.swift
Labels: 네트워킹

#54 [Fix] placedetail에 발생된 constraints 오류 수정
  Projects/App/Sources/UI/Place/PlaceDetail/View/PlaceDetailViewController.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/Views/PlaceInfoHeaderView.swift
Labels: Fix

#62 [Setting] aws-sdk-swift -> aws-sdk-ios-spm 패키지 변경
  .package.resolved
  Projects/App/Project.swift
  Projects/Network/Project.swift
Labels: setting, dependency

#63 [HOTFIX] GoogleService-Info 인식 안되는 문제 수정
  Projects/App/Resources/GoogleService-Info.plist
Labels: Fix

#55 [Design] placeListCell UI
  Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Cell/WholePlaceCell.swift
  Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Views/EmojiCountStackView.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Views/GradientView.swift
  Projects/App/Sources/UI/Place/PlaceList/ViewModel/PlaceCellVeiwModel.swift
Labels: 🦊 Nick, UI

#69 [Setting] 앱 아이콘 추가와 display Name 변경
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/ic_ZESTY.png
  Projects/App/Sources/Application/Info.plist
Labels: setting

#72 [HOTFIX] dev 브랜치에서 빌드 시 발생하는 오류 수정
  Projects/App/Sources/Domain/MockData/MockData.swift
  Projects/App/Sources/Domain/Place/Place.swift
Labels: Fix

#70 [Design] 대학교 상세정보 뷰 UI
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Sources/UI/Organization/OrgDetail/OrgDetailViewController.swift
  Projects/App/Sources/UI/Organization/OrgDetail/View/OrgDatailInformationView.swift
  Projects/DesignSystem/Resources/Assets.xcassets/img_categoryfriends_western.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_categoryfriends_western.imageset/img_categoryfriends_western.png
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends_photo.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends_photo.imageset/img_reviewfriends_photo.png
  Projects/DesignSystem/Sources/Asset/Asset.swift
Labels: 🥒 Min, UI

#73 [Desgin] PlaceListViewController UI
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Sources/Domain/Place/Place.swift
  Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
  Projects/App/Sources/UI/User/Profile/View/ProfileNickNameView.swift
  Projects/DesignSystem/Resources/Colors.xcassets/Color.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/gray54.colorset/Contents.json
  Projects/DesignSystem/Sources/Color/Color.swift
Labels: 🦊 Nick, UI

#74 [Fix] 검색결과 간헐적으로 VC 쌓이는 문제해결
  Projects/App/Sources/UI/Place/AddPlace/View/AddPlaceSearchViewController.swift
  Projects/App/Sources/UI/Place/AddPlace/View/Cell/SearchResultCell.swift
  Projects/App/Sources/UI/Place/AddPlace/ViewModel/AddPlaceSearchViewModel.swift
  Projects/App/Sources/UI/User/Profile/View/ProfileNickNameView.swift
Labels: Fix

#75 Chore:broom:: addSubview 제거
  Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
Labels: 🦊 Nick, UI

#77 [Feat] MainTitleView 높이 제약 제거 + FullWidthBlackButton 비활성화시 색상 적용
  Projects/App/Sources/UI/Place/AddPlace/View/AddCategoryViewController.swift
  Projects/DesignSystem/Sources/Component/FullWidthBlackButton.swift
  Projects/DesignSystem/Sources/Component/MainTitleView.swift
Labels: 🥑 Avo, 🎨 DesignSystem

#78 [Design] 맛집등록결과 UI 수정 및 공유하기 기능추가
  Projects/App/Sources/Domain/Place/AddPlace/PlaceResult.swift
  Projects/App/Sources/Global/Extension/UIScreen+.swift
  Projects/App/Sources/UI/Place/AddPlace/View/AddPlaceResultViewController.swift
  Projects/App/Sources/UI/Place/AddPlace/View/Views/PlaceCard.swift
Labels: 🎄 Avery, UI

#76 [HOTFIX] 프로필 뷰 UI 수정 및 dev 브랜치 오류 수정
  Projects/App/Sources/UI/User/Profile/ProfileViewController.swift
  Projects/App/Sources/UI/User/Profile/View/ProfileLinkButtonView.swift
  Projects/App/Sources/UI/User/Profile/View/ProfileLinkLabelView.swift
  Projects/App/Sources/UI/User/Profile/View/ProfileMenuView.swift
  Projects/App/Sources/UI/User/Profile/View/ProfileUserMenuView.swift
Labels: 🥒 Min, UI

#66 [Feat] 맛집 리스트 API 연결
  Projects/App/.swiftlint.yml
  Projects/App/Sources/Domain/Place/PlaceUseCase.swift
  Projects/App/Sources/Domain/Review/Review.swift
  Projects/App/Sources/Global/Extension/UIImageView+.swift
  Projects/App/Sources/Global/Utility/ErrorMapper.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
  Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Views/EmojiCountStackView.swift
  Projects/App/Sources/UI/Place/PlaceList/ViewModel/PlaceListViewModel.swift
  Projects/App/Sources/UI/Review/ViewModel/ReviewRegisterViewModel.swift
  Projects/DesignSystem/Resources/Assets.xcassets/img_categoryfriends.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_categoryfriends.imageset/img_categoryfriends.svg
  Projects/DesignSystem/Resources/Assets.xcassets/img_errorfriends.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/img_errorfriends.imageset/img_errorfriends.svg
  Projects/DesignSystem/Sources/Asset/Asset.swift
  Projects/Network/Sources/API/PlaceAPI.swift
  Projects/Network/Sources/DTO/ResponseDTO/PlaceListDTO.swift
Labels: 네트워킹, UI

#80 [Feat] AWS S3 imageUploadManager 생성
  Projects/App/Sources/Application/Info.plist
  Projects/DesignSystem/Project.swift
  Projects/Network/Project.swift
  Projects/Network/Sources/AWS/AWSS3ImageManager.swift
  Projects/Network/Sources/AWS/ImageUploadError.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: 네트워킹
