Repository DeveloperAcademy-POSTECH/MacC-TEAM-ZESTY, pull requests merged in 2022-11, with the labels that each got.

#82 [Release] 테스트 플라이트를 위해 작성한 뷰 연결, 오류수정
  Projects/App/Sources/Domain/Place/Place.swift
  Projects/App/Sources/Domain/Review/Review.swift
  Projects/App/Sources/Domain/Review/ReviewRegisterUseCase.swift
  Projects/App/Sources/Global/Extension/UIImageView+.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/PlaceDetailViewController.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/Views/PlaceInfoHeaderView.swift
  Projects/App/Sources/UI/Place/PlaceDetail/ViewModel/PlaceDetailViewModel.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
  Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
  Projects/App/Sources/UI/Place/PlaceList/ViewModel/PlaceListViewModel.swift
  Projects/App/Sources/UI/Review/View/ReviewCardViewController.swift
  Projects/App/Sources/UI/Review/View/ReviewRegisterViewController.swift
  Projects/App/Sources/UI/Review/View/Views/ReviewCardView.swift
  Projects/App/Sources/UI/Review/ViewModel/ReviewRegisterViewModel.swift
  Projects/App/Sources/UI/User/Login/View/ThirdPartyLoginViewController.swift
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_bad.imageset/Contents.json
  Projects/Network/Sources/DTO/ResponseDTO/PlaceListDTO.swift
  Projects/Network/Sources/DTO/ResponseDTO/ReviewDetailDTO.swift
Labels: UI, Fix

#87 [Fix] 맛집 리스트 crash 현상 및 레이아웃 깨짐 이슈 해결
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/App/Sources/Domain/Category/Category.swift
  Projects/App/Sources/Domain/Place/Place.swift
  Projects/App/Sources/Domain/Place/PlaceUseCase.swift
  Projects/App/Sources/Domain/Review/Review.swift
  Projects/App/Sources/Domain/User/User.swift
  Projects/App/Sources/Global/Extension/NavigationBar+.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
  Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Views/ReviewPageView.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Views/SegmentHeaderView.swift
  Projects/App/Sources/UI/Place/PlaceList/ViewModel/PlaceListViewModel.swift
Labels: bug, UI, Fix, Refactor

#88 [Design] 대학교 이메일 인증 뷰 UI
  Projects/App/Sources/UI/Organization/VerifyCode/View/VerifingCodeViewController.swift
  Projects/App/Sources/UI/Organization/VerifyCode/View/Views/OTPStackView.swift
  Projects/App/Sources/UI/Organization/VerifyCode/View/Views/OTPTextField.swift
  Projects/DesignSystem/Sources/Component/MainTitleView.swift
Labels: 🦊 Nick, UI

#83 [Design] 대학교 이메일 입력 뷰 UI
  Projects/App/Sources/UI/Organization/DomainSetting/View/DomainSettingViewController.swift
  Projects/App/Sources/UI/Organization/DomainSetting/ViewModel/DomainSettingViewModel.swift
  Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
Labels: 🦊 Nick, UI

#90 [Design] 대학교 리스트 화면 UI
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Sources/Global/Extension/UITableView+.swift
  Projects/App/Sources/UI/Organization/OrganizationList/View/Cell/OrganizationListCell.swift
  Projects/App/Sources/UI/Organization/OrganizationList/View/OrganizationListViewController.swift
  Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
  Projects/App/Sources/UI/Place/AddPlace/View/AddPlaceSearchViewController.swift
  Projects/DesignSystem/Sources/TextField/SearchTextField.swift
Labels: 🦊 Nick, UI

#94 [Setting] cancelbag 변수로 변경 & previewDevice 추가
  Scripts/ZESTY_VC.xctemplate/___FILEBASENAME___ViewController.swift
Labels: setting, Fix

#85 [Feat] 애플 로그인 및 자동 로그인 기능 구현
  Projects/App/App.entitlements
  Projects/App/Project.swift
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Sources/Domain/User/UserLoginUseCase.swift
  Projects/App/Sources/Domain/User/UserSignupUseCase.swift
  Projects/App/Sources/Global/Extension/UserDefaults+.swift
  Projects/App/Sources/UI/User/Login/View/ThirdPartyLoginViewController.swift
  Projects/App/Sources/UI/User/Login/ViewModel/ThirdPartyLoginViewModel.swift
  Projects/App/Sources/UI/User/Signup/ViewModel/SignupCompleteViewModel.swift
  Projects/Network/Sources/API/UserAPI.swift
  Projects/Network/Sources/DTO/ResponseDTO/User/UserOauthDTO.swift
  Projects/Network/Sources/DTO/ResponseDTO/User/UserProfileDTO.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: WIP

#93 [DesignSystem] 색상 + 폰트 시스템
  Projects/DesignSystem/Resources/Assets.xcassets/img_reviewfriends/img_reviewfriends_bad.imageset/bad.svg
  Projects/DesignSystem/Resources/Colors.xcassets/Gray/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Gray/gray30.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Gray/gray42.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Gray/gray4A.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Gray/gray54.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Gray/gray8D.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Gray/gray99.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Gray/grayD0.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Gray/grayF2.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Gray/grayF6.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Legacy/Color.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Legacy/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Legacy/background.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Legacy/dim.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Legacy/disabled.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Legacy/gray3C.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Legacy/gray3C3C43.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Legacy/grayC5.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Legacy/point.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Legacy/whiteEBEBF5.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Pure/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Pure/black.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Pure/clear.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Pure/white.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Red/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/Red/red01.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/bluegray/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/bluegray/bluegray01.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/bluegray/bluegray02.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/bluegray/bluegray03.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/bluegray/bluegray04.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors.xcassets/grayF6.colorset/Contents.json
  Projects/DesignSystem/Sources/Color/Color.swift
  Projects/DesignSystem/Sources/Color/UIColor+.swift
  Projects/DesignSystem/Sources/Font/Font.swift
  Projects/DesignSystem/Sources/Font/SourcesFontHolder.swift
  Projects/DesignSystem/Sources/Font/UIFont+.swift
Labels: 🥑 Avo, 🎨 DesignSystem

#96 [Fix] 선정 맛집 초기 fetch 안 되는 버그 수정
  Projects/App/Sources/UI/Place/PlaceDetail/View/PlaceDetailViewController.swift
  Projects/App/Sources/UI/Place/PlaceDetail/ViewModel/PlaceDetailViewModel.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
  Projects/App/Sources/UI/Place/PlaceList/ViewModel/PlaceListViewModel.swift
  Projects/App/Sources/UI/Place/SearchPlace/View/SearchPlaceViewController.swift
Labels: bug, Fix

#98 [Feat] 대학교 이메일 입력 도메인 & 네트워킹
  Projects/App/Sources/Domain/Organization/DomainSettingUseCase.swift
  Projects/App/Sources/Domain/User/UserSignupUseCase.swift
  Projects/App/Sources/UI/Organization/DomainSetting/View/DomainSettingViewController.swift
  Projects/App/Sources/UI/Organization/DomainSetting/ViewModel/DomainSettingViewModel.swift
  Projects/App/Sources/UI/Organization/OrganizationList/View/OrganizationListViewController.swift
  Projects/Network/Sources/API/UserAPI.swift
Labels: 네트워킹, 🦊 Nick, WIP

#95 [Fix] 리뷰 중복 추가 수정
  Projects/App/Sources/Domain/MockData/MockData.swift
  Projects/App/Sources/Domain/Place/Place.swift
  Projects/App/Sources/Domain/Review/Review.swift
  Projects/App/Sources/Domain/Review/ReviewRegisterUseCase.swift
  Projects/App/Sources/Domain/User/User.swift
  Projects/App/Sources/Global/Extension/UIImageView+.swift
  Projects/App/Sources/Global/Utility/ErrorMapper.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/Cell/ReviewCell.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/Views/PlaceInfoHeaderView.swift
  Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
  Projects/App/Sources/UI/Review/View/EvaluationViewController.swift
  Projects/App/Sources/UI/Review/View/ReviewCardViewController.swift
  Projects/App/Sources/UI/Review/View/ReviewRegisterViewController.swift
  Projects/App/Sources/UI/Review/View/Views/ReviewCardView.swift
  Projects/App/Sources/UI/Review/ViewModel/ReviewRegisterViewModel.swift
  Projects/Network/Sources/AWS/AWSS3ImageManager.swift
Labels: bug, UI, Fix, Refactor

#99 [Feat] 조직상세페이지 API 연결
  Projects/App/Sources/Domain/Organization/OrganizationDetail/OrganizationDetailUseCase.swift
  Projects/App/Sources/UI/Organization/OrgDetail/View/OrgDetailViewController.swift
  Projects/App/Sources/UI/Organization/OrgDetail/View/Views/OrgDatailInformationView.swift
  Projects/App/Sources/UI/Organization/OrgDetail/ViewModel/OrgDetailViewModel.swift
  Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
  Projects/Network/Sources/API/OrganizationAPI.swift
  Projects/Network/Sources/DTO/ResponseDTO/Organization/OrgDetailDTO.swift
  Projects/Network/Sources/DTO/ResponseDTO/Organization/OrganizationListDTO.swift
Labels: 🎄 Avery

#102 [Fix] cell 재사용으로 인한 UI bug 수정
  Projects/App/Sources/UI/Place/PlaceList/View/Cell/PlaceCell.swift
  Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Views/ReviewPageView.swift
  Projects/App/Sources/UI/Place/PlaceList/ViewModel/PlaceListViewModel.swift
Labels: bug, UI, Fix

#103 [Fix] 이미지 업로드 실패 메시지와 리뷰 등록 실패 메시지 분리
  Projects/App/Sources/UI/Review/View/ReviewCardViewController.swift
  Projects/App/Sources/UI/Review/View/ReviewRegisterViewController.swift
  Projects/App/Sources/UI/Review/ViewModel/ReviewRegisterViewModel.swift
Labels: bug, Fix

#100 [Setting & Feat] Firebase Analytics 설정 및 각각의 페이지에 이벤트 추가
  Projects/App/Resources/GoogleService-Info.plist
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/App/Sources/UI/Organization/DomainSetting/View/DomainSettingViewController.swift
  Projects/App/Sources/UI/Organization/OrgDetail/View/OrgDetailViewController.swift
  Projects/App/Sources/UI/Organization/OrganizationList/View/OrganizationListViewController.swift
  Projects/App/Sources/UI/Organization/VerifyCode/View/VerifingCodeViewController.swift
  Projects/App/Sources/UI/Place/AddPlace/View/AddCategoryViewController.swift
  Projects/App/Sources/UI/Place/AddPlace/View/AddPlaceResultViewController.swift
  Projects/App/Sources/UI/Place/AddPlace/View/AddPlaceSearchViewController.swift
  Projects/App/Sources/UI/Place/AddPlace/View/Cell/CategoryIconCell.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/PlaceDetailViewController.swift
  Projects/App/Sources/UI/Place/PlaceDetail/View/Views/PlaceInfoHeaderView.swift
  Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Views/SegmentHeaderView.swift
  Projects/App/Sources/UI/Place/SearchPlace/View/SearchPlaceViewController.swift
  Projects/App/Sources/UI/Review/View/EvaluationViewController.swift
  Projects/App/Sources/UI/Review/View/ReviewCardViewController.swift
  Projects/App/Sources/UI/Review/View/ReviewRegisterViewController.swift
  Projects/App/Sources/UI/User/Login/View/ThirdPartyLoginViewController.swift
  Projects/App/Sources/UI/User/Profile/ProfileViewController.swift
  Projects/App/Sources/UI/User/Signup/View/NickNameInputViewController.swift
  Projects/App/Sources/UI/User/Signup/View/SignupCompleteViewController.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/ProjectDescriptionHelpers/SettingDictionary.swift
Labels: 🥒 Min, setting, Analytics

#97 [Feat] 대학교 리스트 검색 도메인 & 네트워킹
  Projects/App/Sources/Domain/Organization/DomainSettingUseCase.swift
  Projects/App/Sources/Domain/Organization/OrganizationUseCase.swift
  Projects/App/Sources/Domain/User/UserSignupUseCase.swift
  Projects/App/Sources/UI/Organization/DomainSetting/View/DomainSettingViewController.swift
  Projects/App/Sources/UI/Organization/DomainSetting/ViewModel/DomainSettingViewModel.swift
  Projects/App/Sources/UI/Organization/OrganizationList/View/Cell/OrganizationListCell.swift
  Projects/App/Sources/UI/Organization/OrganizationList/View/OrganizationListViewController.swift
  Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
  Projects/Network/Sources/API/UserAPI.swift
Labels: 네트워킹, 🦊 Nick

#108 [Feat] profileView 닉네임 표시 및 변경
  Projects/App/Sources/Domain/User/UserNicknameUseCase.swift
  Projects/App/Sources/Domain/User/UserSignupUseCase.swift
  Projects/App/Sources/UI/User/Login/View/ThirdPartyLoginViewController.swift
  Projects/App/Sources/UI/User/Profile/View/ProfileViewController.swift
  Projects/App/Sources/UI/User/Profile/View/Views/ProfileNickNameView.swift
  Projects/App/Sources/UI/User/Profile/ViewModel/ProfileViewModel.swift
  Projects/App/Sources/UI/User/Signup/View/NickNameInputViewController.swift
  Projects/App/Sources/UI/User/Signup/ViewModel/NickNameInputViewModel.swift
Labels: enhancement

#109 Fix🐞: 필요없는 useCase 제거
  Projects/App/Sources/Domain/User/UserSignupUseCase.swift
Labels: bug

#106 [Feat] 인증 코드 입력 네트워크 & 도메인 입력 완료 뷰 연결
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Sources/Domain/Organization/DomainSettingUseCase.swift
  Projects/App/Sources/Domain/Organization/VerifingCodeUseCase.swift
  Projects/App/Sources/Domain/User/UserInfoManager.swift
  Projects/App/Sources/UI/Organization/DomainSetting/View/DomainSettingViewController.swift
  Projects/App/Sources/UI/Organization/DomainSetting/ViewModel/DomainSettingViewModel.swift
  Projects/App/Sources/UI/Organization/OrganizationList/View/OrganizationListViewController.swift
  Projects/App/Sources/UI/Organization/VerifyCode/View/DomainSettingCompleteViewController.swift
  Projects/App/Sources/UI/Organization/VerifyCode/View/VerifingCodeViewController.swift
  Projects/App/Sources/UI/Organization/VerifyCode/View/Views/OTPStackView.swift
  Projects/App/Sources/UI/Organization/VerifyCode/ViewModel/DomainSettingCompleteViewModel.swift
  Projects/App/Sources/UI/Organization/VerifyCode/ViewModel/VerifingCodeViewModel.swift
  Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
  Projects/App/Sources/UI/User/Signup/View/NickNameInputViewController.swift
  Projects/App/Sources/UI/User/Signup/View/SignupCompleteViewController.swift
  Projects/Network/Sources/API/UserAPI.swift
  Projects/Network/Sources/DTO/RequestDTO/VerifyCodeDTO.swift
Labels: 네트워킹, 🦊 Nick

#110 [Feat] 맛집리스트 empty view 설정 및 리뷰 등록 메뉴 입력 필수 설정
  Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
  Projects/App/Sources/UI/Review/View/ReviewRegisterViewController.swift
  Projects/DesignSystem/Sources/Component/FullWidthBlackButton.swift
Labels: UI, Fix

#115 [Hotfix] 리뷰등록 메뉴명과 사진에 따른 버튼 UI & 맛집리스트 refreshControl
  Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
  Projects/App/Sources/UI/Place/PlaceList/ViewModel/PlaceListViewModel.swift
  Projects/App/Sources/UI/Review/View/ReviewRegisterViewController.swift
Labels: UI, Fix

#118 [Fix] 서버 API 이슈에 따른 대학교 이메일 인증 로직 변경 & 타이머 시간 멈춤 기능 추가
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Sources/Domain/Organization/DomainSettingUseCase.swift
  Projects/App/Sources/Domain/Organization/VerifingCodeUseCase.swift
  Projects/App/Sources/UI/Organization/DomainSetting/View/DomainSettingViewController.swift
  Projects/App/Sources/UI/Organization/DomainSetting/ViewModel/DomainSettingViewModel.swift
  Projects/App/Sources/UI/Organization/VerifyCode/View/VerifingCodeViewController.swift
  Projects/App/Sources/UI/Organization/VerifyCode/ViewModel/VerifingCodeViewModel.swift
  Projects/Network/Sources/API/UserAPI.swift
Labels: 🦊 Nick, Fix

#121 [Hotfix] 대학교 이메일 입력 뷰에 이메일 중복 검사 추가
  Projects/App/Sources/Domain/Organization/DomainSettingUseCase.swift
  Projects/App/Sources/UI/Organization/DomainSetting/View/DomainSettingViewController.swift
  Projects/App/Sources/UI/Organization/DomainSetting/ViewModel/DomainSettingViewModel.swift
  Projects/App/Sources/UI/Organization/VerifyCode/View/VerifingCodeViewController.swift
  Projects/App/Sources/UI/Organization/VerifyCode/ViewModel/VerifingCodeViewModel.swift
  Projects/Network/Sources/API/UserAPI.swift
Labels: 네트워킹, 🦊 Nick

#119 [Fix] 장소상세 - 사진없는 리뷰 필터링
  Projects/App/Sources/UI/Place/PlaceDetail/ViewModel/PlaceDetailViewModel.swift
Labels: Fix

#123 [Hotfix] 서버API 변동에 따른 오류 수정
  Projects/App/Sources/Domain/Organization/VerifingCodeUseCase.swift
  Projects/App/Sources/Domain/Place/AddPlace/AddPlaceUseCase.swift
  Projects/App/Sources/Domain/Place/PlaceSearch/PlaceSearchUseCase.swift
  Projects/App/Sources/Domain/Place/PlaceUseCase.swift
  Projects/App/Sources/Domain/User/UserInfoManager.swift
  Projects/App/Sources/UI/Organization/DomainSetting/View/DomainSettingViewController.swift
  Projects/App/Sources/UI/Organization/OrgDetail/View/OrgDetailViewController.swift
  Projects/App/Sources/UI/Organization/VerifyCode/ViewModel/VerifingCodeViewModel.swift
  Projects/App/Sources/UI/Place/PlaceList/View/PlaceListViewController.swift
  Projects/App/Sources/UI/Place/PlaceList/View/Views/ExplanationPopOverViewController.swift
  Projects/Network/Sources/API/PlaceAPI.swift
  Projects/Network/Sources/API/UserAPI.swift
  Projects/Network/Sources/DTO/RequestDTO/SignUpUserDTO.swift
  Projects/Network/Sources/DTO/ResponseDTO/User/UserProfileDTO.swift
  Projects/Network/Sources/Service/NetworkService.swift
Labels: bug

#124 [Fix] 소문자 검색 시 대문자로 된 대학 이름 검색 안되는 현상 해결
  Projects/App/Sources/UI/Organization/OrganizationList/ViewModel/OrganizatinoListViewModel.swift
Labels: 🦊 Nick, Fix
